// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAppQZ_aKN5d2L9rhtPhZ7z60BqwriNZGs',
    appId: '1:1000497758448:web:a31293936fe00505b6c235',
    messagingSenderId: '1000497758448',
    projectId: 'gomaa-4ea40',
    authDomain: 'gomaa-4ea40.firebaseapp.com',
    storageBucket: 'gomaa-4ea40.appspot.com',
    measurementId: 'G-3CCQNV036B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPw-ZkbJxoYUu6N5yqh_Hprt4jRFoKE3s',
    appId: '1:1000497758448:android:cd5a04febb3988a4b6c235',
    messagingSenderId: '1000497758448',
    projectId: 'gomaa-4ea40',
    storageBucket: 'gomaa-4ea40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzWv5hcXy_yR6wLaWd1kzsEdVa7Z_c8Ic',
    appId: '1:1000497758448:ios:fb7dd8adba87f7d1b6c235',
    messagingSenderId: '1000497758448',
    projectId: 'gomaa-4ea40',
    storageBucket: 'gomaa-4ea40.appspot.com',
    iosBundleId: 'com.example.gomaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzWv5hcXy_yR6wLaWd1kzsEdVa7Z_c8Ic',
    appId: '1:1000497758448:ios:3952d294e995fbbbb6c235',
    messagingSenderId: '1000497758448',
    projectId: 'gomaa-4ea40',
    storageBucket: 'gomaa-4ea40.appspot.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAppQZ_aKN5d2L9rhtPhZ7z60BqwriNZGs',
    appId: '1:1000497758448:web:a655862648bb1a66b6c235',
    messagingSenderId: '1000497758448',
    projectId: 'gomaa-4ea40',
    authDomain: 'gomaa-4ea40.firebaseapp.com',
    storageBucket: 'gomaa-4ea40.appspot.com',
    measurementId: 'G-75RCTNHM9T',
  );
}
